[package]
name = "OS_Scripts"
version = "1.70.0"
edition = "2021"

[dependencies]
util = {path = "/mnt/Master/Documents/Rust/Rust_Generics"}

[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.52.0"